modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="star_mao"
credits="Original Scannable by Florian 'Sangar' Nucke (MightyPirates), licensed under MIT"
description='''
Unofficial NeoForge port of Scannable — a handheld scanner mod with swappable modules.
Original mod by Florian "Sangar" Nucke (MightyPirates). MIT licensed.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    ordering="NONE"
    side="CLIENT"
