modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
displayName="${mod_name}"
version="${mod_version}"
modId="${mod_id}"
updateJSONURL = "https://api.modrinth.com/updates/scannable-unofficial/forge_updates.json?neoforge=only"
credits="Original Scannable by Florian 'Sangar' Nucke (MightyPirates)"
authors="star_mao"
description='''Unofficial Scannable'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    ordering="NONE"
    side="CLIENT"
